<?php

namespace UB\CoreBundle\Repository;

/**
 * CategorySignalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorySignalRepository extends \Doctrine\ORM\EntityRepository
{
}
