<?php

namespace UB\CoreBundle\Repository;

/**
 * JokerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JokerRepository extends \Doctrine\ORM\EntityRepository
{
}
