<?php

namespace UB\CoreBundle\Repository;

/**
 * RopeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RopeRepository extends \Doctrine\ORM\EntityRepository
{
}
