<?php

namespace UB\CoreBundle\Repository;

/**
 * StaticWinJokerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaticWinJokerRepository extends \Doctrine\ORM\EntityRepository
{
}
