<?php

namespace UB\CoreBundle\Repository;

/**
 * SymboleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SymboleRepository extends \Doctrine\ORM\EntityRepository
{
}
